version: "3.9"
services:
    postgres:
      image: postgres
      restart: always
      environment:
        - POSTGRES_DB=postgresdb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5433:5432'
      extra_hosts:
        - 'host.docker.internal:127.0.0.1'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 10s
        retries: 5
    test:
      image: "exercise-5"
      volumes:
        - .:/app
      command: python3 -m pytest
    run:
      image: "exercise-5"
      depends_on:
        postgres:
          condition: service_healthy
      volumes:
        - .:/app
      command: python3 main.py
